version: '3'
services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7.41-debian
    restart: always
    ports:
      - 3306:3306
    env_file:
      - ./core-admin/.env
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    stop_grace_period: 0s
    networks:
      - tokopolis_network

  zookeeper:
    image: bitnami/zookeeper:latest
    restart: always
    ports:
      - 12181:12181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_PORT_NUMBER=12181
    networks:
      - tokopolis_network

  kafka:
    image: bitnami/kafka:latest
    restart: always
    ports:
      - 19092:19092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:19092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:19092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:12181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - tokopolis_network

  # All services

  service-admin:
    container_name: service-admin
    build: ./core-admin
    ports:
      - "3001:3001"
    links:
      - mysql
    depends_on:
      - mysql
    networks:
      - tokopolis_network

  service-client:
    container_name: service-client
    build: ./core-client
    ports:
      - "3002:3002"
    links:
      - service-admin
    networks:
      - tokopolis_network

  service-email:
    container_name: service-email
    build: ./email-service
    networks:
      - tokopolis_network

  service-payment:
    container_name: service-payment
    build: ./payment-service
    ports:
      - "5123:5123"
    links:
      - service-admin
    networks:
      - tokopolis_network

  service-payment-test:
    container_name: service-payment-test
    build: ./payment-test
    ports:
      - "5125:5125"
    links:
      - service-payment
    networks:
      - tokopolis_network

  # Proxy

  api-gateway:
    build: .
    tty: true
    links:
      - service-admin
      - service-client
      - service-payment-test
    ports:
      - "80:80"
    restart: always
    depends_on:
      - service-admin
      - service-client
      - service-payment-test

networks:
  tokopolis_network:
    name: tokopolis_network
    driver: bridge
