version: '3'
services:
  mysql:
    container_name: mysql
    platform: linux/x86_64
    image: mysql:5.7.37
    restart: always
    ports:
      - 33051:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    stop_grace_period: 0s
    networks:
      - internal

  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper:latest
    restart: always
    ports:
      - 12181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_PORT_NUMBER=2181
    networks:
      - internal

  kafka:
    container_name: kafka
    image: bitnami/kafka:latest
    restart: always
    ports:
      - 19092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ENABLE_KRAFT=false
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - internal

  nginx:
    container_name: api-gateway
    build: .
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./volumes/nginx:/etc/nginx/conf.d
      - ./volumes/certbot/conf:/etc/letsencrypt
      - ./volumes/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: always
    networks:
      - internal

  certbot:
    image: certbot/certbot
    volumes:
      - ./volumes/certbot/conf:/etc/letsencrypt
      - ./volumes/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  internal:
    driver: bridge
