services:
  wms-shipment:
    build:
      context: .
      target: development
    restart: always
    ports:
      - 9601:9601
    env_file:
      - .env
    volumes:
      - ../wms-v2:/app/wms-v2
      - .:/app/wms-shipment
    stop_grace_period: 0s
    networks:
      - hasura_warmindo
networks:
  hasura_warmindo:
    external: true
