name: Deploy Docker Core System

on:
  pull_request:
    branches: [ master ]
    types: [ closed ]
    paths:
      - 'core-admin/**'
      - 'core-client/**'
      - 'email-service/**'
      - 'payment-service/**'

env:
  folderPath: /var/www/html/tokopolis

jobs:
  build:
    name: Build Docker Containers
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Change Working directory
      run: cd ${{ env.folderPath }}
      shell: sh
      working-directory: ${{ env.folderPath }}

    - name: Run Deploy Script
      run: |
        make build