name: Deploy Core System

on:
  pull_request:
    branches: [ master ]
    types: [ closed ]
    paths:
      - 'core-admin/**'
      - 'core-client/**'
      - 'email-service/**'
      - 'payment-service/**'

env:
  folderPath: /var/www/html/tokopolis
  adminFolderName: core-admin
  adminVirtualName: tokopolis-admin
  clientFolderName: core-client
  clientVirtualName: tokopolis-client
  emailFolderName: email-service
  emailVirtualName: tokopolis-email
  paymentFolderName: payment-service
  paymentVirtualName: tokopolis-payment

jobs:
  get-all-files:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy All Files to Destination
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "${{ env.adminFolderName }}/*,${{ env.clientFolderName }}/*"
        target: "${{ env.folderPath }}"

  install-admin:
    needs: get-all-files
    runs-on: ubuntu-latest

    steps:
    - name: Install All Package for Admin
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          cd ${{ env.folderPath }}/${{ env.adminFolderName }}
          npm install

  install-client:
    needs: get-all-files
    runs-on: ubuntu-latest

    steps:
    - name: Install All Package for Client
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          cd ${{ env.folderPath }}/${{ env.clientFolderName }}
          npm install

  install-email:
    needs: get-all-files
    runs-on: ubuntu-latest

    steps:
    - name: Install All Package for Email
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          cd ${{ env.folderPath }}/${{ env.emailFolderName }}
          go mod tidy

  install-payment:
    needs: get-all-files
    runs-on: ubuntu-latest

    steps:
    - name: Install All Package for Payment
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          cd ${{ env.folderPath }}/${{ env.paymentFolderName }}
          npm install

  build-admin:
    needs: [install-admin, install-client, install-email, install-payment]
    runs-on: ubuntu-latest

    steps:
    - name: Build Core Admin
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          cd ${{ env.folderPath }}/${{ env.adminFolderName }}
          npm run build

  build-client:
    needs: build-admin
    runs-on: ubuntu-latest

    steps:
    - name: Build Core Client
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          cd ${{ env.folderPath }}/${{ env.clientFolderName }}
          npm run build

  build-email:
    needs: build-client
    runs-on: ubuntu-latest

    steps:
    - name: Build Email Service
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          cd ${{ env.folderPath }}/${{ env.emailFolderName }}
          go build main.go

  build-payment:
    needs: build-email
    runs-on: ubuntu-latest

    steps:
    - name: Build Core Payment
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          cd ${{ env.folderPath }}/${{ env.paymentFolderName }}
          npm run build

  deploy:
    needs: [build-admin, build-client, build-email, build-payment]
    runs-on: ubuntu-latest

    steps:
    - name: Deploy and Restart Virtual Server
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          pm2 delete ${{ env.adminVirtualName }}
          pm2 delete ${{ env.clientVirtualName }}
          pm2 delete ${{ env.emailVirtualName }}
          pm2 delete ${{ env.paymentVirtualName }}

          cd ~${{ env.folderPath }}/${{ env.adminFolderName }}
          pm2 start npm --name "${{ env.adminVirtualName }}" -- start

          cd ~${{ env.folderPath }}/${{ env.clientFolderName }}
          pm2 start npm --name "${{ env.clientVirtualName }}" -- start

          cd ~${{ env.folderPath }}/${{ env.emailFolderName }}
          pm2 start ./main --name "${{ env.emailVirtualName }}"

          cd ~${{ env.folderPath }}/${{ env.paymentFolderName }}
          pm2 start npm --name "${{ env.paymentVirtualName }}" -- start