name: Deploy Core System

on:
  pull_request:
    branches: [ master ]
    types: [ closed ]
    paths:
      - 'core-admin/**'
      - 'core-client/**'

env:
  folderPath: /var/www/html/tokopolis
  adminFolderName: core-admin
  adminVirtualName: tokopolis-admin
  clientFolderName: core-client
  clientVirtualName: tokopolis-client

jobs:
  get-all-files:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy All Files to Destination
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "${{ env.adminFolderName }}/*,${{ env.clientFolderName }}/*"
        target: "${{ env.folderPath }}"

  install-admin:
    needs: get-all-files
    runs-on: ubuntu-latest

    steps:
    - name: Install All Package for Admin
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          cd ${{ env.folderPath }}/${{ env.adminFolderName }}
          npm install

  install-client:
    needs: build-admin
    runs-on: ubuntu-latest

    steps:
    - name: Install All Package for Client
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          cd ${{ env.folderPath }}/${{ env.clientFolderName }}
          npm install

  build-admin:
    needs: install-admin
    runs-on: ubuntu-latest

    steps:
    - name: Build Core Admin
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          cd ${{ env.folderPath }}/${{ env.adminFolderName }}
          npm run build
          pm2 delete ${{ env.adminVirtualName }}
          pm2 start npm --name "${{ env.adminVirtualName }}" -- start

  build-client:
    needs: install-client
    runs-on: ubuntu-latest

    steps:
    - name: Build Core Client
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          cd ${{ env.folderPath }}/${{ env.clientFolderName }}
          npm run build
          pm2 delete ${{ env.clientVirtualName }}
          pm2 start npm --name "${{ env.clientVirtualName }}" -- start