name: Deploy Docker Core System

on:
  pull_request:
    branches: [ master ]
    types: [ closed ]
    paths:
      - 'core-admin/**'
      - 'core-client/**'
      - 'email-service/**'
      - 'payment-service/**'

env:
  folderPath: /var/www/html/tokopolis

jobs:
  get-all-files:
    name: Copy All Files
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy All Files to Destination
      uses: appleboy/scp-action@v0.1.4
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "*"
        target: "${{ env.folderPath }}"

  build:
    name: Build Docker Containers
    runs-on: ubuntu-latest

    steps:
    - name: Run Deploy Script
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          cd ${{ env.folderPath }}
          make build